-- MySQL Script generated by MySQL Workbench
-- Tue Jul 28 23:20:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema electric_mon
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema electric_mon
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electric_mon` DEFAULT CHARACTER SET utf8 ;
USE `electric_mon` ;

-- -----------------------------------------------------
-- Table `electric_mon`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` TEXT NOT NULL,
  `is_active` TINYINT NULL DEFAULT 0,
  `flogout` TINYINT NULL DEFAULT 0,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `electric_mon`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`building` (
  `bid` INT NOT NULL AUTO_INCREMENT,
  `bname` TEXT NULL,
  `bprefix` VARCHAR(10) NULL,
  `burl` TEXT NULL,
  PRIMARY KEY (`bid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`floor` (
  `fid` INT NOT NULL AUTO_INCREMENT,
  `fname` TEXT NULL,
  `bid` INT NOT NULL,
  PRIMARY KEY (`fid`),
  INDEX `fk_floor_building1_idx` (`bid` ASC),
  CONSTRAINT `fk_floor_building1`
    FOREIGN KEY (`bid`)
    REFERENCES `electric_mon`.`building` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`room` (
  `rid` INT NOT NULL AUTO_INCREMENT,
  `rname` TEXT NULL,
  `rstatus` TINYINT NULL,
  `fid` INT NOT NULL,
  PRIMARY KEY (`rid`),
  INDEX `fk_room_floor_idx` (`fid` ASC),
  CONSTRAINT `fk_room_floor`
    FOREIGN KEY (`fid`)
    REFERENCES `electric_mon`.`floor` (`fid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`type` (
  `tid` INT NOT NULL AUTO_INCREMENT,
  `tname` TEXT NULL,
  `inf_name` VARCHAR(10) NULL,
  PRIMARY KEY (`tid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`board`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`board` (
  `boid` INT NOT NULL AUTO_INCREMENT,
  `bomac` VARCHAR(20) NULL,
  `register` TINYINT NULL,
  `time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `rid` INT NOT NULL,
  PRIMARY KEY (`boid`),
  INDEX `fk_board_room1_idx` (`rid` ASC),
  CONSTRAINT `fk_board_room1`
    FOREIGN KEY (`rid`)
    REFERENCES `electric_mon`.`room` (`rid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`sensor` (
  `sid` INT NOT NULL AUTO_INCREMENT,
  `sname` TEXT NULL,
  `inf_id` INT NULL,
  `inf_type` VARCHAR(10) NULL,
  `tid` INT NOT NULL,
  `boid` INT NOT NULL,
  PRIMARY KEY (`sid`),
  INDEX `fk_sensor_type1_idx` (`tid` ASC),
  INDEX `fk_sensor_board1_idx` (`boid` ASC),
  CONSTRAINT `fk_sensor_type1`
    FOREIGN KEY (`tid`)
    REFERENCES `electric_mon`.`type` (`tid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sensor_board1`
    FOREIGN KEY (`boid`)
    REFERENCES `electric_mon`.`board` (`boid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`rule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`rule` (
  `ruid` INT NOT NULL AUTO_INCREMENT,
  `rname` TEXT NULL,
  `rjson` TEXT NULL,
  PRIMARY KEY (`ruid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`notify`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`notify` (
  `nid` INT NOT NULL AUTO_INCREMENT,
  `ntoken` TEXT NULL,
  `ntime` INT NULL,
  `nlast_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `user_id` INT NOT NULL,
  INDEX `fk_notify_user1_idx` (`user_id` ASC),
  PRIMARY KEY (`nid`),
  CONSTRAINT `fk_notify_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `electric_mon`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `electric_mon`.`logs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `electric_mon`.`logs` (
  `lid` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`lid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
